name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 9 7 * *" # Run on at 9am on the 7th of every month

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]
    steps:
      - uses: actions/checkout@master

      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples

      - name: tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

  check_fmt_and_docs:
    name: Checking fmt, clippy, and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: setup
        run: |
          rustup component add clippy rustfmt
          rustc --version
      - name: clippy
        run: cargo clippy --tests --examples -- -D warnings

      - name: fmt
        run: cargo fmt --all -- --check

      - name: Docs
        run: cargo doc --no-deps
